#!/usr/bin/env python3
"""Compile GLSL shaders to SPIR-V and generate a C++ header with embedded binaries.

Usage: python3 tools/compile_gpu_shaders.py

Requires: glslc (from Vulkan SDK or shaderc package)
Input:   examples/shaders/triangle.vert, examples/shaders/triangle.frag
Output:  examples/example_gpu_shader_spirv.hpp
"""

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SHADER_DIR = PROJECT_ROOT / "examples" / "shaders"
OUTPUT_HEADER = PROJECT_ROOT / "examples" / "example_gpu_shader_spirv.hpp"

SHADERS = [
    ("desaturate_frag", SHADER_DIR / "desaturate.frag", "frag"),
    ("triangle_vert", SHADER_DIR / "triangle.vert", "vert"),
    ("triangle_frag", SHADER_DIR / "triangle.frag", "frag"),
]


def compile_shader(input_path, stage):
    """Compile a single shader with glslc and return the SPIR-V bytes."""
    result = subprocess.run(
        ["glslc", f"-fshader-stage={stage}", str(input_path), "-o", "-"],
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        print(f"glslc failed for {input_path}:")
        print(result.stderr.decode())
        sys.exit(1)
    if result.stderr:
        print(result.stderr.decode().strip())
    return result.stdout


def format_byte_array(name, data):
    """Format binary data as a C++ const uint8_t array."""
    lines = []
    lines.append(f"static const uint8_t {name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_bytes},")
    lines.append("};")
    lines.append(f"static const size_t {name}_size = {len(data)};")
    return "\n".join(lines)


def generate_header(shader_data):
    """Generate the C++ header file with embedded SPIR-V binaries."""
    header_lines = [
        "// Auto-generated by tools/compile_gpu_shaders.py",
        "// DO NOT EDIT MANUALLY",
        "//",
        "// SPIR-V shader binaries for example_gpu_shader.cpp",
        "// Recompile with: glslc (Vulkan SDK / shaderc package)",
        "",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace gpu_shader {",
        "",
    ]
    for name, data in shader_data:
        header_lines.append(format_byte_array(name, data))
        header_lines.append("")
    header_lines.append("} // namespace gpu_shader")
    header_lines.append("")

    return "\n".join(header_lines)


def main():
    shader_data = []
    for name, path, stage in SHADERS:
        if not path.exists():
            print(f"Error: Shader source not found: {path}")
            sys.exit(1)
        print(f"Compiling {path} ...")
        spirv = compile_shader(path, stage)
        shader_data.append((name, spirv))
        print(f"  -> {len(spirv)} bytes of SPIR-V")

    content = generate_header(shader_data)
    OUTPUT_HEADER.write_text(content)
    print(f"\nGenerated: {OUTPUT_HEADER}")


if __name__ == "__main__":
    main()
