// Auto-generated by nob.c - DO NOT EDIT
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t _binary_assets_button1_png_start[];
extern const size_t _binary_assets_button1_png_size;
extern const uint8_t _binary_assets_button_bg_png_start[];
extern const size_t _binary_assets_button_bg_png_size;
extern const uint8_t _binary_assets_fonts_font_ttf_start[];
extern const size_t _binary_assets_fonts_font_ttf_size;

struct EmbeddedAsset {
    const char* name;
    const uint8_t* data;
    size_t size;
    int fontSize;  // -1 = texture, >= 0 = font
};

inline const EmbeddedAsset g_embeddedAssets[] = {
    {"assets/button1.png", _binary_assets_button1_png_start, _binary_assets_button1_png_size, -1},
    {"assets/button_bg.png", _binary_assets_button_bg_png_start, _binary_assets_button_bg_png_size, -1},
    {"assets/fonts/font.ttf", _binary_assets_fonts_font_ttf_start, _binary_assets_fonts_font_ttf_size, 16},
};
inline const size_t g_embeddedAssetCount = 3;
