// Auto-generated by nob.h embed utilities - DO NOT EDIT
#pragma once
#include <stddef.h>
#include <stdint.h>

// Extern declarations for embedded binary data
// Generated by ld -r -b binary
extern "C" {
extern const uint8_t _binary_assets_button1_png_start[];
extern const uint8_t _binary_assets_button1_png_end[];
extern const uint8_t _binary_assets_button_bg_png_start[];
extern const uint8_t _binary_assets_button_bg_png_end[];
extern const uint8_t _binary_assets_fonts_font_ttf_start[];
extern const uint8_t _binary_assets_fonts_font_ttf_end[];
}

struct EmbeddedAsset {
    const char* name;
    const uint8_t* data;
    size_t size;
    int fontSize;  // -1 = texture, >= 0 = font
};

inline const EmbeddedAsset g_embeddedAssets[] = {
    {"assets/button1.png", _binary_assets_button1_png_start, (size_t)(_binary_assets_button1_png_end - _binary_assets_button1_png_start), -1},
    {"assets/button_bg.png", _binary_assets_button_bg_png_start, (size_t)(_binary_assets_button_bg_png_end - _binary_assets_button_bg_png_start), -1},
    {"assets/fonts/font.ttf", _binary_assets_fonts_font_ttf_start, (size_t)(_binary_assets_fonts_font_ttf_end - _binary_assets_fonts_font_ttf_start), 16},
};
inline const size_t g_embeddedAssetCount = 3;
